'use client';

import { useState } from 'react';
import Link from 'next/link';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

const ARTIFACT_TYPES = [
  'Project Charter',
  'KPI Framework',
  'Data Specification',
  'Stakeholder Deck Outline',
];

const EXAMPLES: Record<string, { name: string; context: string }> = {
  'Project Charter': {
    name: 'Customer 360 Data Platform',
    context: 'Building a unified customer data platform for a retail company with 500 stores. Consolidating data from POS, e-commerce, loyalty program, and CRM. Goal: single customer view for personalized marketing. Budget: €800K. Timeline: 6 months. Team: 3 data engineers, 1 architect, 1 PM.',
  },
  'KPI Framework': {
    name: 'E-Commerce Analytics Revamp',
    context: 'Redesigning the analytics framework for an e-commerce platform doing €50M/year revenue. Current dashboards are outdated and siloed. Need to track customer acquisition, retention, LTV, and operational efficiency. Tools: Snowflake, dbt, Looker.',
  },
  'Data Specification': {
    name: 'HR Data Warehouse Migration',
    context: 'Migrating HR data from on-premise Oracle DB to Azure Synapse. Data includes employee records, payroll, performance reviews, training history, and recruitment pipeline. 15,000 employees across 8 countries. GDPR compliance required.',
  },
  'Stakeholder Deck Outline': {
    name: 'Supply Chain Data Lake',
    context: 'Proposing a data lake for supply chain optimization at a manufacturing company. Combining IoT sensor data, ERP, WMS, and supplier data. Expected ROI: 15% reduction in inventory costs. Presenting to CFO and COO for Phase 2 funding.',
  },
};

export default function ToolPage() {
  const [projectName, setProjectName] = useState('');
  const [context, setContext] = useState('');
  const [artifactType, setArtifactType] = useState(ARTIFACT_TYPES[0]);
  const [result, setResult] = useState('');
  const [loading, setLoading] = useState(false);
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState('');
  const [generationTime, setGenerationTime] = useState(0);

  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!projectName || !context) return;
    setLoading(true);
    setResult('');
    setError('');
    const startTime = Date.now();
    try {
      const res = await fetch('/api/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ projectName, context, artifactType }),
      });
      const data = await res.json();
      if (data.error) {
        setError(data.error);
      } else {
        setResult(data.content);
        setGenerationTime(Math.round((Date.now() - startTime) / 1000));
      }
    } catch {
      setError('Network error. Please check your connection and try again.');
    }
    setLoading(false);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(result);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const loadExample = () => {
    const example = EXAMPLES[artifactType];
    if (example) {
      setProjectName(example.name);
      setContext(example.context);
    }
  };

  const handleDownloadDocx = async () => {
    const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, BorderStyle } = await import('docx');
    
    const lines = result.split('\n');
    const children: InstanceType<typeof Paragraph>[] = [];
    
    // Title page
    children.push(
      new Paragraph({
        children: [new TextRun({ text: projectName, font: 'Calibri', size: 48, bold: true, color: '1a1a2e' })],
        alignment: AlignmentType.CENTER,
        spacing: { before: 2400, after: 200 },
      }),
      new Paragraph({
        children: [new TextRun({ text: artifactType, font: 'Calibri', size: 28, color: '6366f1', italics: true })],
        alignment: AlignmentType.CENTER,
        spacing: { after: 200 },
      }),
      new Paragraph({
        children: [new TextRun({ text: `Generated by DataPM Toolkit — ${new Date().toLocaleDateString()}`, font: 'Calibri', size: 20, color: '666666' })],
        alignment: AlignmentType.CENTER,
        spacing: { after: 600 },
      }),
      new Paragraph({
        border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: '6366f1' } },
        spacing: { after: 400 },
      })
    );
    
    for (const line of lines) {
      const trimmed = line.trim();
      
      if (trimmed.startsWith('## ')) {
        children.push(new Paragraph({
          children: [new TextRun({ text: trimmed.replace(/^##\s*/, '').replace(/[📋📊🗄️🎯]/g, '').trim(), font: 'Calibri', size: 28, bold: true, color: '1a1a2e' })],
          heading: HeadingLevel.HEADING_1,
          spacing: { before: 360, after: 120 },
          border: { bottom: { style: BorderStyle.SINGLE, size: 2, color: 'e5e7eb' } },
        }));
      } else if (trimmed.startsWith('### ')) {
        children.push(new Paragraph({
          children: [new TextRun({ text: trimmed.replace(/^###\s*/, ''), font: 'Calibri', size: 24, bold: true, color: '374151' })],
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 240, after: 80 },
        }));
      } else if (trimmed.startsWith('- **') || trimmed.startsWith('* **')) {
        const match = trimmed.match(/^[-*]\s*\*\*(.+?)\*\*[:\s]*(.*)/);
        if (match) {
          children.push(new Paragraph({
            children: [
              new TextRun({ text: '• ', font: 'Calibri', size: 22 }),
              new TextRun({ text: match[1], font: 'Calibri', size: 22, bold: true }),
              new TextRun({ text: match[2] ? ': ' + match[2] : '', font: 'Calibri', size: 22 }),
            ],
            spacing: { after: 60 },
            indent: { left: 360 },
          }));
        }
      } else if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
        children.push(new Paragraph({
          children: [new TextRun({ text: '• ' + trimmed.replace(/^[-*]\s*/, ''), font: 'Calibri', size: 22 })],
          spacing: { after: 60 },
          indent: { left: 360 },
        }));
      } else if (trimmed.startsWith('|') && trimmed.endsWith('|')) {
        // Table row — render as tab-separated for DOCX simplicity
        if (trimmed.match(/^\|[\s-:|]+\|$/)) continue; // skip separator rows
        const cells = trimmed.split('|').filter(c => c.trim()).map(c => c.trim());
        const isHeader = lines.indexOf(line) >= 0 && 
          lines[lines.indexOf(line) + 1]?.trim().match(/^\|[\s-:|]+\|$/);
        children.push(new Paragraph({
          children: cells.map((cell, i) => new TextRun({ 
            text: (i > 0 ? '  |  ' : '') + cell, 
            font: 'Calibri', 
            size: 20, 
            bold: !!isHeader,
          })),
          spacing: { after: 40 },
          indent: { left: 240 },
        }));
      } else if (trimmed === '') {
        children.push(new Paragraph({ spacing: { after: 80 } }));
      } else {
        // Parse inline bold
        const parts = trimmed.split(/(\*\*.+?\*\*)/);
        const runs = parts.map(part => {
          if (part.startsWith('**') && part.endsWith('**')) {
            return new TextRun({ text: part.slice(2, -2), font: 'Calibri', size: 22, bold: true });
          }
          return new TextRun({ text: part, font: 'Calibri', size: 22 });
        });
        children.push(new Paragraph({
          children: runs,
          spacing: { after: 80 },
        }));
      }
    }
    
    const doc = new Document({
      sections: [{
        properties: {
          page: {
            margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 },
          },
        },
        children,
      }],
    });
    const blob = await Packer.toBlob(doc);
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${projectName.replace(/\s+/g, '_')}_${artifactType.replace(/\s+/g, '_')}.docx`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen flex flex-col bg-gray-950">
      <nav className="border-b border-gray-800/60 px-6 py-4 flex items-center justify-between max-w-5xl mx-auto w-full">
        <Link href="/" className="text-xl font-bold tracking-tight">
          <span className="text-indigo-400">Data</span>PM
        </Link>
        <span className="text-xs text-gray-500 bg-gray-800/50 px-2.5 py-1 rounded-full">beta</span>
      </nav>

      <main className="flex-1 max-w-3xl mx-auto w-full px-6 py-10">
        <div className="mb-8">
          <h1 className="text-3xl font-bold mb-2">Generate an Artifact</h1>
          <p className="text-gray-500 text-sm">Fill in your project details and select an artifact type. AI generates a professional document in seconds.</p>
        </div>

        <form onSubmit={handleGenerate} className="space-y-5 mb-10">
          <div>
            <label className="block text-sm font-medium text-gray-300 mb-1.5">
              Project Name
            </label>
            <input
              type="text"
              required
              value={projectName}
              onChange={(e) => setProjectName(e.target.value)}
              placeholder="e.g. Customer 360 Data Platform"
              className="w-full px-4 py-3 rounded-lg bg-gray-900/80 border border-gray-700/60 text-white placeholder-gray-500 focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500/30 transition"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-300 mb-1.5">
              Project Context
            </label>
            <textarea
              required
              rows={5}
              value={context}
              onChange={(e) => setContext(e.target.value)}
              placeholder="Describe the project: goals, stakeholders, data sources, tech stack, constraints, budget, timeline..."
              className="w-full px-4 py-3 rounded-lg bg-gray-900/80 border border-gray-700/60 text-white placeholder-gray-500 focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500/30 transition resize-y"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-300 mb-1.5">
              Artifact Type
            </label>
            <div className="grid grid-cols-2 gap-2">
              {ARTIFACT_TYPES.map((t) => (
                <button
                  key={t}
                  type="button"
                  onClick={() => setArtifactType(t)}
                  className={`px-4 py-3 rounded-lg border text-sm font-medium transition text-left ${
                    artifactType === t
                      ? 'border-indigo-500 bg-indigo-500/10 text-indigo-300'
                      : 'border-gray-700/60 bg-gray-900/40 text-gray-400 hover:border-gray-600 hover:text-gray-300'
                  }`}
                >
                  {t === 'Project Charter' && '📋 '}
                  {t === 'KPI Framework' && '📊 '}
                  {t === 'Data Specification' && '🗄️ '}
                  {t === 'Stakeholder Deck Outline' && '🎯 '}
                  {t}
                </button>
              ))}
            </div>
          </div>

          <div className="flex gap-3">
            <button
              type="submit"
              disabled={loading}
              className="flex-1 bg-indigo-500 hover:bg-indigo-600 text-white font-semibold px-8 py-3 rounded-lg transition disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {loading ? (
                <span className="flex items-center justify-center gap-2">
                  <svg className="animate-spin h-5 w-5" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none"/>
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"/>
                  </svg>
                  Generating...
                </span>
              ) : 'Generate ✨'}
            </button>
            <button
              type="button"
              onClick={loadExample}
              className="px-4 py-3 rounded-lg border border-gray-700/60 text-gray-400 hover:text-gray-300 hover:border-gray-600 transition text-sm"
              title="Load example inputs"
            >
              Try Example
            </button>
          </div>
        </form>

        {error && (
          <div className="mb-6 p-4 rounded-lg bg-red-500/10 border border-red-500/20 text-red-400 text-sm">
            <p className="font-medium mb-1">⚠️ Generation failed</p>
            <p>{error}</p>
            <button onClick={() => { setError(''); }} className="mt-2 text-red-300 underline text-xs hover:text-red-200">
              Dismiss
            </button>
          </div>
        )}

        {loading && (
          <div className="flex flex-col items-center justify-center py-16">
            <div className="animate-spin rounded-full h-10 w-10 border-2 border-indigo-500 border-t-transparent mb-4"></div>
            <p className="text-gray-400 text-sm">Generating your {artifactType.toLowerCase()}...</p>
            <p className="text-gray-600 text-xs mt-1">This usually takes 10-20 seconds</p>
          </div>
        )}

        {result && !loading && (
          <div>
            <div className="flex items-center gap-3 mb-4">
              <button
                onClick={handleCopy}
                className="text-sm px-4 py-2 rounded-lg bg-gray-800/80 hover:bg-gray-700 border border-gray-700/60 transition flex items-center gap-1.5"
              >
                {copied ? '✓ Copied' : '📋 Copy'}
              </button>
              <button
                onClick={handleDownloadDocx}
                className="text-sm px-4 py-2 rounded-lg bg-gray-800/80 hover:bg-gray-700 border border-gray-700/60 transition flex items-center gap-1.5"
              >
                📄 Download DOCX
              </button>
              <span className="ml-auto text-xs text-gray-600">
                Generated in {generationTime}s
              </span>
            </div>
            <div className="bg-gray-900/80 border border-gray-800/60 rounded-xl p-8 prose prose-invert prose-sm max-w-none prose-headings:text-gray-100 prose-h2:text-xl prose-h2:mt-8 prose-h2:mb-3 prose-h3:text-lg prose-h3:mt-5 prose-h3:mb-2 prose-p:text-gray-300 prose-li:text-gray-300 prose-strong:text-gray-200 prose-table:text-sm prose-th:text-gray-300 prose-td:text-gray-400 prose-th:border-gray-700 prose-td:border-gray-800">
              <ReactMarkdown remarkPlugins={[remarkGfm]}>
                {result}
              </ReactMarkdown>
            </div>
          </div>
        )}
      </main>

      <footer className="border-t border-gray-800/40 px-6 py-4 text-center text-xs text-gray-600">
        Powered by Gemini 2.0 Flash · <Link href="/" className="text-gray-500 hover:text-gray-400 transition">DataPM Toolkit</Link>
      </footer>
    </div>
  );
}
